import * as current from '../generated/hegemony_wasm.js';
import * as previous from '../generated/legacy-v0.2.1/hegemony_wasm.js';
import * as intermediate from '../generated/legacy-v0.2.2/hegemony_wasm.js';
import * as last from '../generated/legacy-v0.2.3/hegemony_wasm.js';
import * as stable from '../generated/legacy-v0.2.4/hegemony_wasm.js';
import * as paced from '../generated/legacy-v0.2.5/hegemony_wasm.js';
import * as attached from '../generated/legacy-v0.2.6/hegemony_wasm.js';
import * as grave from '../generated/legacy-v0.2.7/hegemony_wasm.js';
import * as playable from '../generated/legacy-v0.2.8/hegemony_wasm.js';
import currentModule from '../generated/hegemony_wasm_bg.wasm';
import previousModule from '../generated/legacy-v0.2.1/hegemony_wasm_bg.wasm';
import intermediateModule from '../generated/legacy-v0.2.2/hegemony_wasm_bg.wasm';
import lastModule from '../generated/legacy-v0.2.3/hegemony_wasm_bg.wasm';
import stableModule from '../generated/legacy-v0.2.4/hegemony_wasm_bg.wasm';
import pacedModule from '../generated/legacy-v0.2.5/hegemony_wasm_bg.wasm';
import attachedModule from '../generated/legacy-v0.2.6/hegemony_wasm_bg.wasm';
import graveModule from '../generated/legacy-v0.2.7/hegemony_wasm_bg.wasm';
import playableModule from '../generated/legacy-v0.2.8/hegemony_wasm_bg.wasm';
import { routeKernels } from './kernel-router.mjs';
current.initSync({ module: currentModule });
previous.initSync({ module: previousModule });
intermediate.initSync({ module: intermediateModule });
last.initSync({ module: lastModule });
stable.initSync({ module: stableModule });
paced.initSync({ module: pacedModule });
attached.initSync({ module: attachedModule });
grave.initSync({ module: graveModule });
playable.initSync({ module: playableModule });
export const kernel = routeKernels(current, [previous, intermediate, last, stable, paced, attached, grave, playable]);
