import * as current from '../generated/hegemony_wasm.js';
import currentModule from '../generated/hegemony_wasm_bg.wasm';
import * as legacy1 from '../generated/legacy-v0.2.1/hegemony_wasm.js';
import legacyModule1 from '../generated/legacy-v0.2.1/hegemony_wasm_bg.wasm';
import * as legacy2 from '../generated/legacy-v0.2.2/hegemony_wasm.js';
import legacyModule2 from '../generated/legacy-v0.2.2/hegemony_wasm_bg.wasm';
import * as legacy3 from '../generated/legacy-v0.2.3/hegemony_wasm.js';
import legacyModule3 from '../generated/legacy-v0.2.3/hegemony_wasm_bg.wasm';
import * as legacy4 from '../generated/legacy-v0.2.4/hegemony_wasm.js';
import legacyModule4 from '../generated/legacy-v0.2.4/hegemony_wasm_bg.wasm';
import * as legacy5 from '../generated/legacy-v0.2.5/hegemony_wasm.js';
import legacyModule5 from '../generated/legacy-v0.2.5/hegemony_wasm_bg.wasm';
import * as legacy6 from '../generated/legacy-v0.2.6/hegemony_wasm.js';
import legacyModule6 from '../generated/legacy-v0.2.6/hegemony_wasm_bg.wasm';
import * as legacy7 from '../generated/legacy-v0.2.7/hegemony_wasm.js';
import legacyModule7 from '../generated/legacy-v0.2.7/hegemony_wasm_bg.wasm';
import * as legacy8 from '../generated/legacy-v0.2.8/hegemony_wasm.js';
import legacyModule8 from '../generated/legacy-v0.2.8/hegemony_wasm_bg.wasm';
import * as legacy9 from '../generated/legacy-v0.2.9/hegemony_wasm.js';
import legacyModule9 from '../generated/legacy-v0.2.9/hegemony_wasm_bg.wasm';
import * as legacy10 from '../generated/legacy-v0.2.10/hegemony_wasm.js';
import legacyModule10 from '../generated/legacy-v0.2.10/hegemony_wasm_bg.wasm';
import * as legacy11 from '../generated/legacy-v0.2.11/hegemony_wasm.js';
import legacyModule11 from '../generated/legacy-v0.2.11/hegemony_wasm_bg.wasm';
import * as legacy12 from '../generated/legacy-v0.2.12/hegemony_wasm.js';
import legacyModule12 from '../generated/legacy-v0.2.12/hegemony_wasm_bg.wasm';
import * as legacy13 from '../generated/legacy-v0.2.13/hegemony_wasm.js';
import legacyModule13 from '../generated/legacy-v0.2.13/hegemony_wasm_bg.wasm';
import * as legacy14 from '../generated/legacy-v0.2.14/hegemony_wasm.js';
import legacyModule14 from '../generated/legacy-v0.2.14/hegemony_wasm_bg.wasm';
import * as legacy15 from '../generated/legacy-v0.2.15/hegemony_wasm.js';
import legacyModule15 from '../generated/legacy-v0.2.15/hegemony_wasm_bg.wasm';
import * as legacy16 from '../generated/legacy-v0.2.16/hegemony_wasm.js';
import legacyModule16 from '../generated/legacy-v0.2.16/hegemony_wasm_bg.wasm';
import * as legacy17 from '../generated/legacy-v0.2.17/hegemony_wasm.js';
import legacyModule17 from '../generated/legacy-v0.2.17/hegemony_wasm_bg.wasm';
import * as legacy18 from '../generated/legacy-v0.2.18/hegemony_wasm.js';
import legacyModule18 from '../generated/legacy-v0.2.18/hegemony_wasm_bg.wasm';
import * as legacy19 from '../generated/legacy-v0.2.19/hegemony_wasm.js';
import legacyModule19 from '../generated/legacy-v0.2.19/hegemony_wasm_bg.wasm';
import * as legacy20 from '../generated/legacy-v0.2.20/hegemony_wasm.js';
import legacyModule20 from '../generated/legacy-v0.2.20/hegemony_wasm_bg.wasm';
import * as legacy21 from '../generated/legacy-v0.2.21/hegemony_wasm.js';
import legacyModule21 from '../generated/legacy-v0.2.21/hegemony_wasm_bg.wasm';
import * as legacy22 from '../generated/legacy-v0.2.22/hegemony_wasm.js';
import legacyModule22 from '../generated/legacy-v0.2.22/hegemony_wasm_bg.wasm';
import * as legacy23 from '../generated/legacy-v0.2.23/hegemony_wasm.js';
import legacyModule23 from '../generated/legacy-v0.2.23/hegemony_wasm_bg.wasm';
import * as legacy24 from '../generated/legacy-v0.2.24/hegemony_wasm.js';
import legacyModule24 from '../generated/legacy-v0.2.24/hegemony_wasm_bg.wasm';
import * as legacy25 from '../generated/legacy-v0.2.25/hegemony_wasm.js';
import legacyModule25 from '../generated/legacy-v0.2.25/hegemony_wasm_bg.wasm';
import { routeKernels } from './kernel-router.mjs';
current.initSync({ module: currentModule });
legacy1.initSync({ module: legacyModule1 });
legacy2.initSync({ module: legacyModule2 });
legacy3.initSync({ module: legacyModule3 });
legacy4.initSync({ module: legacyModule4 });
legacy5.initSync({ module: legacyModule5 });
legacy6.initSync({ module: legacyModule6 });
legacy7.initSync({ module: legacyModule7 });
legacy8.initSync({ module: legacyModule8 });
legacy9.initSync({ module: legacyModule9 });
legacy10.initSync({ module: legacyModule10 });
legacy11.initSync({ module: legacyModule11 });
legacy12.initSync({ module: legacyModule12 });
legacy13.initSync({ module: legacyModule13 });
legacy14.initSync({ module: legacyModule14 });
legacy15.initSync({ module: legacyModule15 });
legacy16.initSync({ module: legacyModule16 });
legacy17.initSync({ module: legacyModule17 });
legacy18.initSync({ module: legacyModule18 });
legacy19.initSync({ module: legacyModule19 });
legacy20.initSync({ module: legacyModule20 });
legacy21.initSync({ module: legacyModule21 });
legacy22.initSync({ module: legacyModule22 });
legacy23.initSync({ module: legacyModule23 });
legacy24.initSync({ module: legacyModule24 });
legacy25.initSync({ module: legacyModule25 });
export const kernel = routeKernels(current, [legacy1, legacy2, legacy3, legacy4, legacy5, legacy6, legacy7, legacy8, legacy9, legacy10, legacy11, legacy12, legacy13, legacy14, legacy15, legacy16, legacy17, legacy18, legacy19, legacy20, legacy21, legacy22, legacy23, legacy24, legacy25]);
