import * as current from '../generated/hegemony_wasm.js';
import currentModule from '../generated/hegemony_wasm_bg.wasm';
import * as legacy1 from '../generated/legacy-v0.2.1/hegemony_wasm.js';
import legacyModule1 from '../generated/legacy-v0.2.1/hegemony_wasm_bg.wasm';
import * as legacy2 from '../generated/legacy-v0.2.2/hegemony_wasm.js';
import legacyModule2 from '../generated/legacy-v0.2.2/hegemony_wasm_bg.wasm';
import * as legacy3 from '../generated/legacy-v0.2.3/hegemony_wasm.js';
import legacyModule3 from '../generated/legacy-v0.2.3/hegemony_wasm_bg.wasm';
import * as legacy4 from '../generated/legacy-v0.2.4/hegemony_wasm.js';
import legacyModule4 from '../generated/legacy-v0.2.4/hegemony_wasm_bg.wasm';
import * as legacy5 from '../generated/legacy-v0.2.5/hegemony_wasm.js';
import legacyModule5 from '../generated/legacy-v0.2.5/hegemony_wasm_bg.wasm';
import * as legacy6 from '../generated/legacy-v0.2.6/hegemony_wasm.js';
import legacyModule6 from '../generated/legacy-v0.2.6/hegemony_wasm_bg.wasm';
import * as legacy7 from '../generated/legacy-v0.2.7/hegemony_wasm.js';
import legacyModule7 from '../generated/legacy-v0.2.7/hegemony_wasm_bg.wasm';
import * as legacy8 from '../generated/legacy-v0.2.8/hegemony_wasm.js';
import legacyModule8 from '../generated/legacy-v0.2.8/hegemony_wasm_bg.wasm';
import * as legacy9 from '../generated/legacy-v0.2.9/hegemony_wasm.js';
import legacyModule9 from '../generated/legacy-v0.2.9/hegemony_wasm_bg.wasm';
import * as legacy10 from '../generated/legacy-v0.2.10/hegemony_wasm.js';
import legacyModule10 from '../generated/legacy-v0.2.10/hegemony_wasm_bg.wasm';
import * as legacy11 from '../generated/legacy-v0.2.11/hegemony_wasm.js';
import legacyModule11 from '../generated/legacy-v0.2.11/hegemony_wasm_bg.wasm';
import * as legacy12 from '../generated/legacy-v0.2.12/hegemony_wasm.js';
import legacyModule12 from '../generated/legacy-v0.2.12/hegemony_wasm_bg.wasm';
import * as legacy13 from '../generated/legacy-v0.2.13/hegemony_wasm.js';
import legacyModule13 from '../generated/legacy-v0.2.13/hegemony_wasm_bg.wasm';
import * as legacy14 from '../generated/legacy-v0.2.14/hegemony_wasm.js';
import legacyModule14 from '../generated/legacy-v0.2.14/hegemony_wasm_bg.wasm';
import * as legacy15 from '../generated/legacy-v0.2.15/hegemony_wasm.js';
import legacyModule15 from '../generated/legacy-v0.2.15/hegemony_wasm_bg.wasm';
import * as legacy16 from '../generated/legacy-v0.2.16/hegemony_wasm.js';
import legacyModule16 from '../generated/legacy-v0.2.16/hegemony_wasm_bg.wasm';
import * as legacy17 from '../generated/legacy-v0.2.17/hegemony_wasm.js';
import legacyModule17 from '../generated/legacy-v0.2.17/hegemony_wasm_bg.wasm';
import * as legacy18 from '../generated/legacy-v0.2.18/hegemony_wasm.js';
import legacyModule18 from '../generated/legacy-v0.2.18/hegemony_wasm_bg.wasm';
import * as legacy19 from '../generated/legacy-v0.2.19/hegemony_wasm.js';
import legacyModule19 from '../generated/legacy-v0.2.19/hegemony_wasm_bg.wasm';
import * as legacy20 from '../generated/legacy-v0.2.20/hegemony_wasm.js';
import legacyModule20 from '../generated/legacy-v0.2.20/hegemony_wasm_bg.wasm';
import * as legacy21 from '../generated/legacy-v0.2.21/hegemony_wasm.js';
import legacyModule21 from '../generated/legacy-v0.2.21/hegemony_wasm_bg.wasm';
import * as legacy22 from '../generated/legacy-v0.2.22/hegemony_wasm.js';
import legacyModule22 from '../generated/legacy-v0.2.22/hegemony_wasm_bg.wasm';
import * as legacy23 from '../generated/legacy-v0.2.23/hegemony_wasm.js';
import legacyModule23 from '../generated/legacy-v0.2.23/hegemony_wasm_bg.wasm';
import * as legacy24 from '../generated/legacy-v0.2.24/hegemony_wasm.js';
import legacyModule24 from '../generated/legacy-v0.2.24/hegemony_wasm_bg.wasm';
import * as legacy25 from '../generated/legacy-v0.2.25/hegemony_wasm.js';
import legacyModule25 from '../generated/legacy-v0.2.25/hegemony_wasm_bg.wasm';
import * as legacy25ResourcePolicy from '../generated/legacy-v0.2.25-resource-policy/hegemony_wasm.js';
import legacyModule25ResourcePolicy from '../generated/legacy-v0.2.25-resource-policy/hegemony_wasm_bg.wasm';
import * as legacy26 from '../generated/legacy-v0.2.26/hegemony_wasm.js';
import legacyModule26 from '../generated/legacy-v0.2.26/hegemony_wasm_bg.wasm';
import * as legacy26ResourcePolicy from '../generated/legacy-v0.2.26-resource-policy/hegemony_wasm.js';
import legacyModule26ResourcePolicy from '../generated/legacy-v0.2.26-resource-policy/hegemony_wasm_bg.wasm';
import { routeKernels } from './kernel-router.mjs';
import * as legacy27 from '../generated/legacy-v0.2.27/hegemony_wasm.js';
import legacyModule27 from '../generated/legacy-v0.2.27/hegemony_wasm_bg.wasm';
import * as legacy28 from '../generated/legacy-v0.2.28/hegemony_wasm.js';
import legacyModule28 from '../generated/legacy-v0.2.28/hegemony_wasm_bg.wasm';
import * as legacy29 from '../generated/legacy-v0.2.29/hegemony_wasm.js';
import legacyModule29 from '../generated/legacy-v0.2.29/hegemony_wasm_bg.wasm';
import * as legacy30 from '../generated/legacy-v0.2.30/hegemony_wasm.js';
import legacyModule30 from '../generated/legacy-v0.2.30/hegemony_wasm_bg.wasm';
import * as legacy31 from '../generated/legacy-v0.2.31/hegemony_wasm.js';
import legacyModule31 from '../generated/legacy-v0.2.31/hegemony_wasm_bg.wasm';
import * as legacy32 from '../generated/legacy-v0.2.32/hegemony_wasm.js';
import legacyModule32 from '../generated/legacy-v0.2.32/hegemony_wasm_bg.wasm';
import * as legacy33 from '../generated/legacy-v0.2.33/hegemony_wasm.js';
import legacyModule33 from '../generated/legacy-v0.2.33/hegemony_wasm_bg.wasm';
import { lazyKernel } from './lazy-kernel.mjs';
const kernel0 = lazyKernel(current, currentModule, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.31-mill-public-candidate","engineVersion":"rust-v0.2.34-mill-public-candidate"});
const kernel1 = lazyKernel(legacy1, legacyModule1, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.1","engineVersion":"rust-v0.2.1"});
const kernel2 = lazyKernel(legacy2, legacyModule2, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.1","engineVersion":"rust-v0.2.2"});
const kernel3 = lazyKernel(legacy3, legacyModule3, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.2","engineVersion":"rust-v0.2.3"});
const kernel4 = lazyKernel(legacy4, legacyModule4, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.2","engineVersion":"rust-v0.2.4"});
const kernel5 = lazyKernel(legacy5, legacyModule5, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.3","engineVersion":"rust-v0.2.5"});
const kernel6 = lazyKernel(legacy6, legacyModule6, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.4","engineVersion":"rust-v0.2.6"});
const kernel7 = lazyKernel(legacy7, legacyModule7, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.5","engineVersion":"rust-v0.2.7"});
const kernel8 = lazyKernel(legacy8, legacyModule8, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.6","engineVersion":"rust-v0.2.8"});
const kernel9 = lazyKernel(legacy9, legacyModule9, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.6","engineVersion":"rust-v0.2.9"});
const kernel10 = lazyKernel(legacy10, legacyModule10, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.7","engineVersion":"rust-v0.2.10"});
const kernel11 = lazyKernel(legacy11, legacyModule11, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.8","engineVersion":"rust-v0.2.11"});
const kernel12 = lazyKernel(legacy12, legacyModule12, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.9-jc008-candidate","engineVersion":"rust-v0.2.12-jc008-candidate"});
const kernel13 = lazyKernel(legacy13, legacyModule13, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.10-msjc01-candidate","engineVersion":"rust-v0.2.13-msjc01-candidate"});
const kernel14 = lazyKernel(legacy14, legacyModule14, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.11-yellow-search-batch-candidate","engineVersion":"rust-v0.2.14-yellow-search-batch-candidate"});
const kernel15 = lazyKernel(legacy15, legacyModule15, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.12-control-type-batch-candidate","engineVersion":"rust-v0.2.15-control-type-batch-candidate"});
const kernel16 = lazyKernel(legacy16, legacyModule16, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.13-renown-batch-candidate","engineVersion":"rust-v0.2.16-renown-batch-candidate"});
const kernel17 = lazyKernel(legacy17, legacyModule17, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.14-protection-batch-candidate","engineVersion":"rust-v0.2.17-protection-batch-candidate"});
const kernel18 = lazyKernel(legacy18, legacyModule18, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.15-defence-equipment-candidate","engineVersion":"rust-v0.2.18-defence-equipment-candidate"});
const kernel19 = lazyKernel(legacy19, legacyModule19, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.16-equipment-abilities-candidate","engineVersion":"rust-v0.2.19-equipment-abilities-candidate"});
const kernel20 = lazyKernel(legacy20, legacyModule20, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.17-hand-deck-candidate","engineVersion":"rust-v0.2.20-hand-deck-candidate"});
const kernel21 = lazyKernel(legacy21, legacyModule21, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.18-hand-interactions-candidate","engineVersion":"rust-v0.2.21-hand-interactions-candidate"});
const kernel22 = lazyKernel(legacy22, legacyModule22, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.19-purple-tools-candidate","engineVersion":"rust-v0.2.22-purple-tools-candidate"});
const kernel23 = lazyKernel(legacy23, legacyModule23, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.20-wound-defence-candidate","engineVersion":"rust-v0.2.23-wound-defence-candidate"});
const kernel24 = lazyKernel(legacy24, legacyModule24, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.21-dream-reveal-candidate","engineVersion":"rust-v0.2.24-dream-reveal-candidate"});
const kernel25 = lazyKernel(legacy25, legacyModule25, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.22-repress-assets-candidate","engineVersion":"rust-v0.2.25-repress-assets-candidate"});
const kernel25ResourcePolicy = lazyKernel(legacy25ResourcePolicy, legacyModule25ResourcePolicy, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.22-repress-assets-candidate","engineVersion":"rust-v0.2.25-resource-policy-candidate"});
const kernel26 = lazyKernel(legacy26, legacyModule26, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.23-msjc07-candidate","engineVersion":"rust-v0.2.26-msjc07-candidate"});
const kernel26ResourcePolicy = lazyKernel(legacy26ResourcePolicy, legacyModule26ResourcePolicy, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.23-msjc07-candidate","engineVersion":"rust-v0.2.26-msjc07-resource-policy-candidate"});
const kernel27 = lazyKernel(legacy27, legacyModule27, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.24-white-wound-society-candidate","engineVersion":"rust-v0.2.27-white-wound-society-candidate"});
const kernel28 = lazyKernel(legacy28, legacyModule28, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.25-purple-region-society-candidate","engineVersion":"rust-v0.2.28-purple-region-society-candidate"});
const kernel29 = lazyKernel(legacy29, legacyModule29, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.26-msjc11-mixed-deck-candidate","engineVersion":"rust-v0.2.29-msjc11-mixed-deck-candidate"});
const kernel30 = lazyKernel(legacy30, legacyModule30, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.27-jc029-reuse-candidate","engineVersion":"rust-v0.2.30-jc029-reuse-candidate"});
const kernel31 = lazyKernel(legacy31, legacyModule31, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.28-green-minimum-candidate","engineVersion":"rust-v0.2.31-green-minimum-candidate"});
const kernel32 = lazyKernel(legacy32, legacyModule32, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.29-jc030-blue-bat-candidate","engineVersion":"rust-v0.2.32-jc030-blue-bat-candidate"});
const kernel33 = lazyKernel(legacy33, legacyModule33, {"rulesVersion":"hegemony-pdf-v1","cardPoolVersion":"limited-v2.30-blue-minimum-candidate","engineVersion":"rust-v0.2.33-blue-minimum-candidate"});
export const kernel = routeKernels(kernel0, [kernel1, kernel2, kernel3, kernel4, kernel5, kernel6, kernel7, kernel8, kernel9, kernel10, kernel11, kernel12, kernel13, kernel14, kernel15, kernel16, kernel17, kernel18, kernel19, kernel20, kernel21, kernel22, kernel23, kernel24, kernel25, kernel25ResourcePolicy, kernel26, kernel26ResourcePolicy, kernel27, kernel28, kernel29, kernel30, kernel31, kernel32, kernel33]);
